# Generated by Django 4.1.5 on 2023-06-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingapplications',
            name='reason_for_denial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
